name: cloudbakers
description: "A new Flutter project."
# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Versioning information
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: ^3.7.0

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.1  # Added shared_preferences

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Add assets directory for images and translations
  assets:
    - assets/images/  # Includes all images inside this folder