// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0LwEJXdkCYSL1WHELp2AJ7DiQO76EbwU',
    appId: '1:786374840248:web:07fbecbbded1c40cc7494d',
    messagingSenderId: '786374840248',
    projectId: 'cloudbakers-1b4b3',
    authDomain: 'cloudbakers-1b4b3.firebaseapp.com',
    storageBucket: 'cloudbakers-1b4b3.firebasestorage.app',
    measurementId: 'G-5RPRF9683R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeuC5wkvoaqFQpnyBjkF-Yh06vw9K3PJo',
    appId: '1:786374840248:android:f3b0d9f267d7a030c7494d',
    messagingSenderId: '786374840248',
    projectId: 'cloudbakers-1b4b3',
    storageBucket: 'cloudbakers-1b4b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg4Ro9AxkrzpO6PjDYPRzN55o6-YRYFP4',
    appId: '1:786374840248:ios:bec8e120ae37f58bc7494d',
    messagingSenderId: '786374840248',
    projectId: 'cloudbakers-1b4b3',
    storageBucket: 'cloudbakers-1b4b3.firebasestorage.app',
    iosClientId: '786374840248-269gjs2ilf1t8nojif5hp438shfkip2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudbakers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg4Ro9AxkrzpO6PjDYPRzN55o6-YRYFP4',
    appId: '1:786374840248:ios:bec8e120ae37f58bc7494d',
    messagingSenderId: '786374840248',
    projectId: 'cloudbakers-1b4b3',
    storageBucket: 'cloudbakers-1b4b3.firebasestorage.app',
    iosClientId: '786374840248-269gjs2ilf1t8nojif5hp438shfkip2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudbakers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0LwEJXdkCYSL1WHELp2AJ7DiQO76EbwU',
    appId: '1:786374840248:web:614956ed8b66324ac7494d',
    messagingSenderId: '786374840248',
    projectId: 'cloudbakers-1b4b3',
    authDomain: 'cloudbakers-1b4b3.firebaseapp.com',
    storageBucket: 'cloudbakers-1b4b3.firebasestorage.app',
    measurementId: 'G-PWEG9459LX',
  );
}
