name: cloudbakers
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  image_picker: ^1.1.2
  shared_preferences: ^2.2.1
  http: ^1.3.0
  path_provider: ^2.1.1
  googleapis: ^14.0.0
  googleapis_auth: ^1.2.0
  google_fonts: ^6.2.1

  # 🔥 Firebase dependencies  
  firebase_core: ^3.12.1  # Ensure latest version  
  firebase_auth: ^5.5.1  
  google_sign_in: ^6.3.0  
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vision_credentials.json
    - assets/.env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"
